### ISSUE TITLE
Representing uncertainty in inferred maps

### ISSUE THREAD

**Issue by fbartolic** [fbartolic/volcano#11]
I've been trying out a few different ways of representing uncertainty on inferred maps. Here are some examples with a linear fit to mock occultations in emitted light.

![image](https://user-images.githubusercontent.com/18243408/76434432-0b0a0a00-638c-11ea-9b24-c24406a25ebf.png)

One option is to have a plot of the mean map (summed over posterior samples in pixel space) and a separate map for the standard deviation or inverse variance. This is shown below
![image](https://user-images.githubusercontent.com/18243408/76434495-2412bb00-638c-11ea-8949-277bf3e9f85f.png)

Another option is to make uncertain parts of the map more transparent, this requires matplotlib `3.2.0` where `alpha` can be an array in `imshow`.  There a few different ways of mapping uncertainties to alpha values and I've plotted a few I could think of below:

![image](https://user-images.githubusercontent.com/18243408/76435418-5c66c900-638d-11ea-8faa-5523a2a73b24.png)

I quite like the second approach, in particular the ones where alpha is scaled by the precision (inverse variance). It makes it obvious that only one side of the occulted object was visible during occultation and all spurious features have high transparency. 

All of these plots look a lot prettier in anotebook!

Let me know what you think @dfm @rodluger

**Comment by dfm** [comment]
Very cool!! I really like the alpha versions as well - I think it does a great job of communicating the uncertainty. We might need to think about which version is the clearest, but I like it.
