### ISSUE TITLE
Add ORCIDs for authors

### ISSUE THREAD

**Issue by dfm** [fbartolic/volcano#19]
AASTeX supports this, I think.

Mine is: 0000-0002-9328-5652

**Comment by rodluger** [comment]
```
\author[0000-0002-0296-3826]{Rodrigo Luger}
```

**Comment by fbartolic** [comment]
I added all orcids to the tex but they're not showing up in the pdf, is that how it should be @rodluger ?

**Comment by rodluger** [comment]
Doing this

https://github.com/rodluger/starrynight/blob/a8b79beddf1878b9776a8bf9820f7b73322a2115/tex/ms.tex#L27

should make the author names clickable (linking to their ORCID profile). Is that not what's happening?

**Comment by fbartolic** [comment]
Ah yes, I didn't notice they became clickable, thanks!
